ohsu-comp-bio/funnel

src/tes/storage/local.go
src/tes/worker/util.go
src/tes/worker/worker.go

Quick fix for file permissions issue in containers with non-root users.

Local storage refactor

---

src/funnel/tests/funnel.go

Trying to resolve some intermittent issues with tests in TravisCI

Add server start sleep

---

src/funnel/worker/worker.go

Initial connection logging in worker

---

src/funnel/worker/runner.go

Remove TODO related to #24 which is already resolved.

Remove resolved TODO

---

src/funnel/cmd/task/cancel.go
src/funnel/cmd/task/client.go
src/funnel/cmd/task/client_test.go
src/funnel/cmd/task/create.go
src/funnel/cmd/task/get.go
src/funnel/cmd/task/list.go
src/funnel/cmd/task/task.go

Working towards making the `funnel task` commands testable.

Refactor to make task cmds testable

---

cmd/examples/examples.go
cmd/task/task.go
cmd/worker/worker.go

Command aliases

---

Makefile
website/content/_index.md
website/layouts/index.html
website/static/css/funnel.css

Tweak website content to hide holes and TODOs

---

cmd/server/server.go
server/server.go

This already bit me again, so here's an improvement.

Handle and log server start errors

---

storage/local.go
storage/local_test.go

Default to "file://" for storage URL scheme

---

cmd/server/server.go
scheduler/manual/sched.go

Closes #26 
Needed for setting up a cluster manually for the grid learn stuff.

Manual (generic) worker scheduler

---

.gitmodules
Makefile
logger/log.go
logger/text_formatter.go
tests/fmt/fmt.go

Log format upgrade

---

.gitmodules
Makefile
proto/tes/validate.go
proto/tes/validate_test.go
server/task_boltdb.go
tests/e2e/utils.go
tests/e2e/validation_test.go
tests/fmt/fmt.go
tests/funnel.go

Closes #56 
Still needs a few more tests for individual validations.

Task validation

---

cmd/client/client.go
server/task_boltdb.go
tests/e2e/basic_test.go
tests/e2e/utils.go
tests/funnel_test.go

The HTTP endpoints for this are broken due to: https://github.com/grpc-ecosystem/grpc-gateway/issues/166
So, yet another reason to figure out how to upgrade grpc gateway.

Get/List task views (#70)

---

Makefile
website/content/install.md

Already uploaded the release and updated the website.

Minor changes to build and website for 0.1.0

---

storage/gs.go
storage/storage.go
tests/e2e/basic_test.go
tests/e2e/s3_test.go
tests/e2e/storage_test.go
tests/e2e/utils.go
tests/e2e/validation_test.go
tests/testutils/utils.go
util/docker.go

I'll use this to test the pagination PR.
Closes #138 because I had issues with this during testing.
Also needed to modify the Google Storage backend slightly to better handle the case where auth details are missing.

Reusable e2e test server

---

cmd/termdash/compact/main.go
cmd/termdash/config/switch.go
cmd/termdash/expanded/main.go
cmd/termdash/grid.go
cmd/termdash/keys.go
cmd/termdash/menus.go
cmd/termdash/tasksource.go
cmd/termdash/termdash.go
cmd/termdash/widgets/header.go

Rather than panicking, the dashboard will render and an error will appear in the header portion of the UI.

termdash: fix panic, reverse order, full task IDs, cleanup

---

server/server.go

Remove stack trace from http error handler

---

config/bundle.go
examples/bundle.go
server/task_boltdb.go
tests/e2e/basic_test.go

404 when canceling a nonexistent task; fixed basic task view

---

cmd/root.go
cmd/task/task.go
cmd/task/wait.go

Related to #199 
`funnel wait` seems out of place. This PR moves it to `funnel task wait`

Move wait cli command to task wait

---

logger/grpc.go
tests/e2e/utils.go

Helps with log spam in E2E tests

grpc logger now uses V2 interface

---

Makefile
cmd/root.go
cmd/server/server.go
cmd/version/data.go
cmd/version/generate_data.sh
cmd/version/version.go
worker/worker.go

Add versioning info to build, cmds, and logs

---

worker/step.go

Inspecting the container was happening in a loop with no timer, so that during startup the logs are spammed with thousands of error messages.
This PR adds a timer to that loop. Probably fixes #80 but that will need to be tested manually.

Add timer around inspect container loop

---

cmd/run/cmd_test.go
cmd/run/flags.go
cmd/run/parse_vars.go
cmd/run/usage.go
tests/e2e/auth/auth_test.go
tests/e2e/basic_test.go
tests/e2e/gce/gce_test.go
tests/e2e/gridengine/gridengine_test.go
tests/e2e/htcondor/htcondor_test.go
tests/e2e/pbs/pbs_test.go
tests/e2e/perf/perf_test.go
tests/e2e/s3/s3_test.go
tests/e2e/slurm/slurm_test.go
tests/e2e/storage_test.go
tests/e2e/worker_test.go

* better local path handling
* cmds run via sh -c by default
closes #243 
closes #168

funnel run bug fixes

---

.gitmodules
Makefile
config/config.go
events/log_writer.go
storage/s3.go
storage/storage.go
storage/storage_test.go
tests/e2e/s3/s3_test.go
tests/e2e/utils.go

amazon s3 storage backend

---

.buildbot
Makefile
config/config.go
config/default-config.yaml
storage/storage.go
storage/swift.go
tests/e2e/openstack/openstack_test.go

Swift storage backend

---

cmd/gce/gce.go
cmd/server/run.go
compute/scheduler/scheduler.go
tests/e2e/server_cmd_test.go
tests/e2e/utils.go

Fix for server panic with manual backend. Also trying out a shell test for this fix.

Fix server panic on manual backend

---

worker/docker.go

docker: pull before run

---

cmd/examples/examples.go

cli: write example data to stdout

---

cmd/run/flags.go

fix funnel run '--server' flag

---

cmd/node/run.go
cmd/server/run.go
cmd/worker/run.go
compute/gce/mock.go
compute/local/backend.go
compute/scheduler/node.go
compute/scheduler/scheduler.go
config/config.go
server/boltdb/events.go
server/elastic/events.go
server/elastic/tes.go
tests/e2e/es.config.yml
tests/e2e/node/node_test.go
tests/e2e/utils.go
tests/e2e/worker_test.go
worker/dynamodb_taskreader.go
worker/rpc_taskreader.go
worker/worker.go

Elastic event writer

---

worker/docker.go
worker/step.go

I noticed from docker daemon logs that inspect container still spams docker every millisecond with inspect requests. Since we're removing the need for it soon by removing ports from the TES spec, here we go.

docker: remove inspect container

---

.buildbot
.travis.yml
Makefile
cmd/worker/run.go
compute/scheduler/testutils_test.go
config/config.go
events/json.go
events/kafka.go
events/log_writer.go
events/rpc_writer.go
events/task.go
events/task_builder.go
events/writer.go
kafka.config.yml
server/dynamodb/events.go
server/elastic/events.go
server/mongodb/new.go
tests/e2e/kafka/worker_test.go
tests/e2e/worker_test.go
worker/interfaces.go
worker/noop.go
worker/worker.go

Kafka events

---

examples/bundle.go
examples/resource-request.json
examples/s3.json

Closes #307 
Turns out most of these are fixed by TES v0.3

Fix example case names

---

config/config.go
examples/bundle.go
storage/storage_test.go
storage/swift.go
tests/e2e/utils.go

swift: detect config from env

---

client/client.go
client/client_test.go
cmd/run/cmd_test.go
cmd/termdash/expanded/main.go
proto/tes/utils.go
server/server.go

I added JSON pretty printing, because why not.

server: indents for JSON responses

---

docs/download/index.html
docs/index.xml
website/content/download.md

Updated download page to note homebrew install instructions.

release: homebrew website docs

---

cmd/termdash/compact/grid.go
cmd/termdash/config/main.go
cmd/termdash/cursor.go
cmd/termdash/expanded/main.go
cmd/termdash/expanded/taskjson.go
cmd/termdash/grid.go
cmd/termdash/keys.go
cmd/termdash/tasksource.go
config/bundle.go
examples/bundle.go

Also brings back page up and page down:
fn-up
fn-down

termdash: err handling in expanded view

---

server/dynamodb/events.go

Follow up from the discussion here: https://github.com/ohsu-comp-bio/funnel/pull/328#pullrequestreview-77555809
Note that I duplicated some code from `GetTask`, which will be de-duplicated by #328 
Happy to add other events to the test if needed.

Dynamo event cleanup

---

server/elastic/events.go
server/elastic/scheduler.go

elastic: fix sort order

---

client/client.go
client/client_test.go
cmd/node/node.go
cmd/run/cmd.go
cmd/server/server.go
cmd/task/cancel.go
cmd/task/create.go
cmd/task/get.go
cmd/task/list.go
cmd/task/task.go
cmd/task/task_test.go
cmd/task/wait.go
cmd/termdash/cursor.go
cmd/termdash/tasksource.go
cmd/termdash/termdash.go
cmd/worker/worker.go
tests/funnel_utils.go

Fixed cmd/task/list panic; cmd/dashboard server env var; more validation

---

events/systemlog.go
server/boltdb/events.go
server/dynamodb/events.go
server/elastic/events.go
server/mongodb/events.go

added 'task_attempt', 'executor_index' and 'timestamp' fields to syslogs

---

cmd/task/task.go
cmd/task/task_test.go
cmd/termdash/termdash.go

cmd/task: ensure server flag overrides env var

---

.gitmodules
storage/swift.go

swift: min/max chunk size

---

storage/local.go

While attempting to run [bunny](https://github.com/rabix/bunny) using a FUSE + Swift setup, I ran into a failure in the Funnel local storage backend. The FUSE library only supports create, read-only, and write-only file modes, while Go's `os.Create` uses a read-write mode.
This PR includes all the error messages I needed to add to track down the problem, and a change to use create + write-only for local file copy.
This PR needs a little work maybe, putting it here so I don't forget about it.

storage/local: add error messages. create|wronly copy mode

---

storage/amazon_s3.go
storage/generic_s3.go
storage/gs.go
storage/local.go
storage/swift.go

Adds more consistency in closing files opened for writing. 
Ensuring parent dirs exist for downloads.

Storage: Closing file handles; ensure hostPath

---

cmd/util/flags.go
config/config.go

The lesson of this PR is that we need to start using [roger](https://github.com/buchanae/roger) or something like it to generate these flags.

cli: added missing flags

---

server/elastic/scheduler.go
server/mongodb/scheduler.go
tests/scheduler/scheduler_test.go

test Scheduler.ReadQueue sort oder

---

Makefile

forgot to clean this up in the last release changes.

build: remove unused github token

---

cmd/server/run.go
events/writer.go
tests/scheduler/scheduler_test.go

server: correctly handle cancel event for manual backend

---

cmd/node/node.go
cmd/node/run.go
cmd/server/server.go
cmd/worker/worker.go
compute/scheduler/client.go
compute/scheduler/node.go
compute/scheduler/node_test.go
compute/scheduler/testutils_test.go

fix signal handling delay for cancelling the entrypoint context

---

compute/scheduler/scheduler.go
tests/config_utils.go
tests/funnel_utils.go
tests/scheduler/node_test.go

compute/scheduler: fix node task cleanup restart edge case

---

.gitignore
Makefile
webdash/debug.sh
webdash/package-lock.json
webdash/package.json

Extracting the webdash build/dev script I wrote for #453

webdash: debug/dev script

---

cmd/server/run.go
compute/batch/backend.go
compute/gridengine/backend.go
compute/hpc_backend.go
compute/hpc_backend_test.go
compute/htcondor/backend.go
compute/local/backend.go
compute/pbs/backend.go
compute/slurm/backend.go
server/tes.go
tests/gridengine/gridengine_test.go
tests/htcondor/htcondor_test.go
tests/pbs/pbs_test.go
tests/pbs/resources/torque.setup
tests/slurm/resources/Dockerfile
tests/slurm/resources/slurm.conf
tests/slurm/resources/slurmdbd.conf
tests/slurm/slurm_test.go

Cancel queued tasks in AWS Batch, HTCondor, Slurm, etc.
closes #327

compute: cancel queued tasks; log failed Compute.Submit calls

---

cmd/server/run.go

Fixed bug that allowed an event writer to be included in the multiwriter more than once

Server run event writer initialization bug fix

---

config/default-config.yaml
docs/funnel-config-examples/default-config.yaml
website/content/docs/security/basic.md
website/static/funnel-config-examples/default-config.yaml

Missed some docs and default config for #505

auth: update default config and website docs

---

events/executor.go
events/task_builder.go
tests/core/worker_test.go
util/ring/ring.go
util/ring/ring_test.go

fix for stdout/err log tail collection

---

tests/core/worker_test.go
worker/docker.go
worker/step.go

worker/docker: log container metadata

---

cmd/aws/batch/config.go
cmd/util/flags.go
compute/batch/backend.go
compute/htcondor/backend.go
compute/pbs/backend.go
compute/scheduler/node.go
compute/scheduler/node_test.go
compute/scheduler/node_util.go
compute/scheduler/scheduler.go
compute/scheduler/testutils_test.go
compute/slurm/backend.go
config/config.go
config/default-config.yaml
config/default.go
config/duration.go
database/mongodb/new.go
storage/http.go
storage/http_test.go
tests/config_utils.go
tests/core/worker_test.go
tests/scheduler/node_health_test.go
tests/scheduler/node_test.go
util/rpc/rpc.go
website/content/docs/compute/deployment.md
website/content/docs/storage/http.md
worker/step.go
worker/worker.go

config: use time.ParseDuration for duration strings

---

config/default-config.yaml
config/default.go
storage/swift.go
website/content/docs/storage/swift.md

storage/swift: default chunk size of 500MB

---

cmd/run/flags.go

cmd/run: remove default workdir

---

tes/hash.go
tes/hash_test.go

Here's a start to call caching: calculating a hash for a given task.

tes: add task hash

---

config/default-config.yaml

Fix HPC templates in default-config.yaml

---

deployments/systemd/funnel-node.service
deployments/systemd/funnel-server.service

I have service files like these scattered all over the place. Committing them here so they're somewhere useful.

docs: example systemd service file for funnel node

---

worker/docker.go

worker: use os/exec to connect to docker

---

config/config.go
storage/amazon_s3.go
tests/core/metrics_test.go
util/aws/session.go
website/content/docs/storage/s3.md
website/static/funnel-config-examples/default-config.yaml

storage/s3: added sse-c and sse-kms support

---

Dockerfile
Makefile
docker/Dockerfile

Changes the docker build to be a staged build that is then copied into a bare alpine image.

Adding new docker build

---

.github/dependabot.yml

Should combine all Dependbot PR's into more manageable groups.

Add groups for Dependabot PR's

---

.github/workflows/compliance.yaml
.github/workflows/k8s.yaml
.github/workflows/nextflow.yaml
.github/workflows/s3.yaml
.github/workflows/tests.yaml
tests/funnel_utils.go

> [!WARNING]
> Work in Progress — currently resolving test failures below ⚠️  
Cleaning up errors in the GitHub Actions workflows.
Current Actions are failing on many workflows due to a mix of dependency issues (`go mod tidy`, deprecated fields).
All actions succeed for all tests defined in the [`.github/workflows`](https://github.com/ohsu-comp-bio/funnel/pull/1195/files) directory

`develop` ← `fix/github-actions` — Update GitHub Actions workflows 🐛 

---

.github/workflows/hugo.yml

Small PR to include [**Pagefind seach**](https://pagefind.app/) on [**Funnel's website**](https://ohsu-comp-bio.github.io/funnel)
<a href="https://ohsu-comp-bio.github.io/funnel">
</a>

fix: update website build in `hugo.yml`
