src/funnel/scheduler/condor/sched.go

Worker resources are requested via condor_submit. 
Worker resources are inherited from the Task message since there is a 1-to-1 mapping between jobs and workers in this backend. 
If worker resources are set in the config this overrides all other behavior and all worker requests get these values.

Worker Resources in Condor Sched

---

src/funnel/cmd/server.go
src/funnel/cmd/worker.go
src/funnel/config/config.go
src/funnel/scheduler/condor/sched.go
src/funnel/scheduler/gce/client.go
src/funnel/scheduler/gce/mocks/Client.go
src/funnel/scheduler/gce/sched.go
src/funnel/scheduler/gce/sched_test.go
src/funnel/scheduler/gce/wrapper_test.go
src/funnel/scheduler/openstack/scaler.go

Since I modified the CLI to read in a full config file these changes were needed.  In the past the worker CLI command expected that the YAML file only contained Worker config.

Fix for worker CLI start

---

src/funnel/cmd/worker.go
src/funnel/config/config.go
src/funnel/worker/worker_test.go

Fixes an panic such as 
```
Apr 11 19:08:47 funnel-worker start-funnel.sh[1570]: panic: non-positive interval for NewTicker
Apr 11 19:08:47 funnel-worker start-funnel.sh[1570]: goroutine 1 [running]:
Apr 11 19:08:47 funnel-worker start-funnel.sh[1570]: time.NewTicker(0x0, 0xd0256e)
Apr 11 19:08:47 funnel-worker start-funnel.sh[1570]: #011/usr/local/Cellar/go/1.8/libexec/src/time/tick.go:23 +0x1b4
Apr 11 19:08:47 funnel-worker start-funnel.sh[1570]: funnel/worker.(*Worker).Run(0xc420199100)
Apr 11 19:08:47 funnel-worker start-funnel.sh[1570]: #011/Users/buchanae/projects/funnel/src/funnel/worker/worker.go:58 +0xa1
Apr 11 19:08:47 funnel-worker start-funnel.sh[1570]: funnel/cmd.startWorker(0xc42029cbc0, 0x32, 0xc42032e4e0, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Apr 11 19:08:47 …
```

Fix bug with worker config merging

---

worker/docker.go
worker/file_mapper.go

We don't need to specify overlapping output volumes since subpaths inherit permissions.

Ensure output volumes don't overlap

---

storage/gs.go
storage/local.go
storage/local_test.go

Encountered some inconsistent behavior that this PR addresses.  Essentially, URLs were being decoded in Get and Put, but not for the contents being recursively copied from a directory.

Local storage path encoding fix

---

cmd/client/client.go

There's something weird I don't understand about the error variable assignment happening here. Go is somehow converting a nil value to a non-nil value. The simple fix was to rename the variable.

Fix error handling in HTTP client validation

---

Makefile
cmd/gce/gce.go
deployments/gce-cos/README.md
deployments/gce-cos/cloud-init.yaml
deployments/gce-cos/make-server.sh
deployments/gce-cos/make-worker-templates.sh
deployments/gce-cos/make-worker.sh
deployments/gce/README.md

This simplifies deployment to Google by using their container-optimized OS (COS) and dockerized funnel. This removes the steps needed to build and deploy a Funnel VM image.
I'm leaving the existing VM-image deployment as is for now, in case it's actually useful to someone, some day. I'll revisit down the road to clean it up if it's not used.

cloud-init + google COS image

---

server/scheduler_service.go
tests/e2e/basic_test.go
tests/e2e/s3/s3_test.go
tests/e2e/utils.go

This makes the e2e test server more reusable by moving the `init()` code to `TestMain()`. The S3 tests also had a TestMain, so that moved into a subpackage to remove that conflict. Also cleaned up an unwanted debug log line.

Use TestMain instead of init

---

storage/local.go
tests/e2e/storage_test.go
util/dir.go

Submitting two tasks that write to the same output location results in a permission denied error in some cases. 
Example:
`funnel run 'sh -c "echo hello world > $OUT; chmod go+w $OUT"' -o OUT=./test_out --container alpine:latest`

fixed bug in local storage backend

---

deployments/gce-cos/cloud-init.yaml
deployments/gce-cos/make-worker-templates.sh
docker/Dockerfile
worker/docker.go

While testing the direct-to-task branch on GCE, a couple issues cropped up:
- the make-worker-templates.sh script was wrong
- the docker image is based on "docker:stable" in that branch, which creates issues with client/server API version mismatches in worker.DockerCmd.Run.
This fixes those. 
During testing, I also had intermittent issues with the VM failing to start because it couldn't get the funnel image from docker hub. I added a "docker pull" to the cloud-init.yaml file to try to mitigate that.
I'll need to update dockerhub when this is merged.

Fix GCE deploy scripts

---

cmd/task/list.go
server/scheduler_service.go
server/task_boltdb.go
tests/e2e/auth/auth_test.go
tests/e2e/basic_test.go

* Fixed panic in `funnel task list`  that occurred when there were zero tasks in the DB.
* GetTask now returns 404 when a request is sent with an unknown task id

ListTask command fix and GetTask endpoint fix

---

.gitattributes
cmd/server/server.go
cmd/version/data.go
scheduler/node.go
server/scheduler_boltdb.go

This fixes few errors had made their way into the logs coming from `funnel server`.
Also, the Node immediately calls `sync()` instead of waiting for the first timer tick (5 seconds)

clean up errors during local node start

---

cmd/node/run.go
config/config.go
server/scheduler_boltdb.go
tests/e2e/node/node_test.go
tests/e2e/node_health_test.go
util/sigctx.go

This improves our handling of dead nodes:
- `node run` now watches for SIGINT and SIGTERM (canceled process) and cancels the node's context. The node the tells the server it's gone, which deletes it from the DB.
- Adds a check for nodes that have been dead for more than 5 minutes, at which point they are deleted.
Hopefully, this will help us handle preempted tasks in the future.

Clean dead nodes on signal and timeout

---

compute/gce/mock.go
tests/e2e/gce/gce_test.go

This fixes the issue where mocks can't be generated due to some import cycle

fix gce mock cycle

---

storage/gs.go
storage/gs_test.go
storage/local.go
storage/local_test.go
storage/s3.go
storage/storage.go
storage/swift.go
tests/e2e/s3/s3_test.go
worker/file_mapper.go
worker/file_mapper_test.go
worker/worker.go

- deduplicated storage code for put
- report container paths in OutputFileLog
closes #290

OutputFileLog.path container path bug fix

---

compute/scheduler/node.go

Handle the error from newWorker by logging it. Move the post-task handling to a defer to ensure the task ID always gets cleaned up. Also catch a panic.
Not a full solution, but an improvement.

Handle node worker err

---

logger/text_formatter.go

This will try to log protobuf messages as json, if possible, which makes makes them easier to read.

logger: log protobuf as json if possible

---

cmd/termdash/config/switch.go
cmd/termdash/cursor.go
cmd/termdash/grid.go
cmd/termdash/keys.go
cmd/termdash/menus.go
cmd/termdash/tasksource.go
cmd/termdash/termdash.go
cmd/termdash/widgets/header.go
cmd/termdash/widgets/input.go

Termdash paging

---

tests/e2e/utils.go

I've seen this fail occasionally, causing TestCancel to be flaky, and I don't think the 5 second timeout is necessary.

tests: remove timeout on docker destroy event wait

---

Makefile
cmd/worker/run.go
compute/hpc_backend.go
compute/scheduler/node.go
config/bundle.go
examples/bundle.go
server/boltdb/new.go
storage/gs.go
storage/swift.go
tests/config_utils.go
tests/funnel_utils.go
util/dockerutil/docker.go
util/fsutil/dir.go
worker/docker.go
worker/file_mapper.go
worker/worker.go

I've been slowly working towards Appengine support. Appengine's sandbox takes issue with certain imports, such as `syscall`. This shuffles some utility code so that the server doesn't depend on these imports.

utils: move fs and docker utils

---

cmd/termdash/grid.go

Otherwise tasks in a terminal state end up with the basic view.

termdash: ensure expanded task widget gets full view

---

cmd/worker/run.go
util/rpc/rpc.go

Related to #184 
This closes rpc client connections made by each task worker.

worker/rpc: close rpc clients

---

compute/scheduler/scheduler.go

`slerr` or `serr` can be nil, which results in a panic when `err.Error()` is called.
`slerr` isn't really needed. It's ok if the system log drops.

compute/scheduler: fix nil panic on error log

---

cmd/node/node.go
cmd/server/server.go
cmd/worker/worker.go
logger/grpc.go
tests/funnel_utils.go

The grpc logs are a pain. In the screenshot below you can see they overwhelm the TravisCI test logs with pages of junk. This is an attempt to clean those up by moving most things to the debug level.
Perhaps one things that's missing is to call SetGRPCLogger in all the top-level commands such as server, node, and worker.

logger/grpc: set most grpc logs to debug

---

cmd/server/run.go
cmd/worker/run.go
server/boltdb/new.go
server/datastore/new.go
server/dynamodb/new.go
server/elastic/new.go
server/mongodb/new.go

Bringing back the `Init` method for our databases. This allows us to scope permissions for the worker differently than the server in cloud environments.

databases: added Init method to interface

---

server/elastic/tes.go
tests/core/basic_test.go

Elasticsearch wasn't correctly returning results from a tag filter

server/elastic: fix tag filter to use keyword

---

worker/docker.go
worker/file_mapper.go
worker/file_mapper_test.go

This is a defensive measure since so many tools seem to write to this location. 
Additionally, I added the `--read-only` flag to the docker run command.  Any location that the command will write to should be declared in `volumes`, `inputs`, or `outputs` in the task message.

worker: always mount to /tmp in container

---

client/client.go
cmd/server/run.go
config/config.go
server/auth.go
server/server.go
tests/auth/auth_test.go

server: configurable user for basic auth

---

storage/swift.go

I needed these while debugging a swift issue.

storage/swift: wrap errors with useful context

---

cmd/completion.go
cmd/gendocs.go
cmd/root.go

I actually started using bash completion (finally). This remove the `Hidden` flag that was hiding the command, and organizes shell command completion under `funnel completion <shell>` e.g. `funnel completion bash`.
By the way, I use `source <(funnel completion bash)` in my profile.

cmd: add completion command for bash completion

---

cmd/node/node_test.go
cmd/server/server_test.go
cmd/util/config.go
cmd/util/config_test.go
cmd/worker/worker_test.go
compute/hpc_backend.go
config/utils.go

Moved the temp file function to a util package, because it was only being used by tests.

config: handle error from ToYaml

---

cmd/task/create.go
cmd/task/task.go
cmd/task/task_test.go
tests/cmd/hello-world.json
tests/cmd/task_create_test.go

I have a script that generates many tasks. This feature allows me to pipe those tasks directly to funnel with `python generate-tasks.py | funnel task create -`. 
In the past I've written the extra code to write these tasks to a bunch of files in a directory, which is an annoying extra step when you're doing this frequently.
To do:

cmd/task/create: read tasks from stdin

---

cmd/run/cmd_test.go
cmd/run/flags.go
cmd/run/usage.go

This code is complex and unused.

cmd/run: remove "extra" args

---

cmd/storage/storage.go

One thing to consider: the interface for put is `put [url] [path]`, which feels backwards, but matches the `Storage` interface. Should we reverse it for the CLI? Reverse it in both the interface and CLI? Leave it?

cmd/storage: add get and put

---

cmd/storage/storage.go
cmd/worker/run.go
config/default.go
storage/mux.go
storage/swift.go
util/retry.go

This PR is not ready, and depends on #551 
This upgrades a number of features of our Swift storage retrier:
- logging messages about when retries are happening
- fixing a bugs in error matching in ShouldRetry
- getting rid of MaxRetries in favor of max elapsed time (closes #475)

storage/swift: better retries and bug fixes

---

.travis.yml
Gopkg.lock
Makefile
cmd/server/run.go
cmd/worker/run.go
config/config.go
config/default-config.yaml
config/default.go
database/badger/events.go
database/badger/new.go
database/badger/tes.go
tes/states.go
tes/utils.go
tests/badger.config.yml
tests/config_utils.go
tests/core/basic_test.go

Depends on #555 
Otherwise is the same as #543 
closes #151

databases: add Badger

---

storage/local.go
storage/local_test.go

Fixes a bug in listing a local directory where the object URL was not correctly constructed.
I included a relative path here just to demonstrate the current behavior, even if it's maybe not technically valid.
https://github.com/ohsu-comp-bio/funnel/compare/master...buchanae:storage/local-fix-join?expand=1#diff-4c0ea73958615f2efed54a943c962e45R130

storage/local: fix directory list url join

---

cmd/node/run.go
cmd/worker/run.go
cmd/worker/worker.go
cmd/worker/worker_test.go
compute/local/backend.go
server/tes.go
tes/utils.go
tests/core/basic_test.go
tests/core/worker_test.go
tests/kafka/worker_test.go
tests/pubsub/pubsub_test.go
tests/scheduler/node_test.go
worker/base64_taskreader.go
worker/file_taskreader.go
worker/interfaces.go
worker/rpc_taskreader.go
worker/taskreader.go
worker/taskreader_test.go
worker/worker.go

@delagoya requested a CLI entrypoint for running the worker on a task file.
This is the 20-minute hack version. It works, but needs some cleanup. Logging is currently broken, so there's no output.
Run as `funnel worker run -f examples/hello-world.json`.

cmd/worker: run task from file

---

.travis.yml
Gopkg.lock
Makefile
config/config.go
config/default.go
storage/ftp.go
storage/mux.go
storage/storage_test.go
tests/config_utils.go
tests/ftp-test-server/.gitignore
tests/ftp-test-server/Dockerfile
tests/ftp-test-server/_scratch/ftp-var/anon-2
tests/ftp-test-server/_scratch/passwd/pureftpd.passwd
tests/ftp-test-server/readme.md
tests/ftp-test-server/start-server.sh
tests/ftp.config.yml
tests/storage/ftp_test.go
website/content/docs/storage/ftp.md

There's a little bit left to do here:
- auth credentials should have a place in the config file. currently the code only supports pulling user/pass from the URL.
That could be done in a future issue though.

storage/ftp: add FTP support

---

Gopkg.lock
Gopkg.toml
database/mongodb/counts.go
database/mongodb/events.go
database/mongodb/new.go
database/mongodb/scheduler.go
database/mongodb/tes.go
logger/grpc.go
server/server.go
server/tes.go
storage/http_test.go
util/rpc/rpc.go
webdash/http.go

database/mongodb: copy session for each op and maintain a connection pool

---

database/mongodb/counts.go

In its current state, MongoDB does not make use of indexes in $group operations within an aggregate pipeline.  If a lot of tasks exist in the db, this means that this simple aggregate -> sum operation will take a long time as it has to access all documents in the db and cannot just use an index. In real world usage, this was the longest frequently running query we noticed in the logs and it caused significant load on our db.
According to the [docs](https://docs.mongodb.com/manual/core/aggregation-pipeline/#aggregation-pipeline-operators-and-performance), $match and $sort both are capable of using said index, and inserting them at the beginning of the aggregate pipeline yields a roughly five and ten-fold decrease in query runtime, respectively (according to 1k test queries run by …

Optimize TaskStateCounts aggregate pipeline

---

deployments/kubernetes/README.md
docs/docs/compute/kubernetes/index.html
docs/docs/index.xml
docs/download/index.html
docs/index.html
docs/index.xml
website/content/docs/compute/kubernetes.md

I found a broken link in the docs. This fixes it and rebuilds the website. It looks like the website build also picked up the latest release.

Fix link to Kubernetes deployments in docs

---

.github/workflows/nextflow.yaml
.github/workflows/tests.yaml
server/server.go

- Updates 'unsupported backends' response code (Error code 400 instead of 500)
- TES Compliance Test: https://github.com/elixir-cloud-aai/openapi-test-runner/blob/dev/tests/create_task_backend_parameters_negative.yml#L32-L35
- Updates Nextflow workflow to use correct branch (`master` instead of `tes-update-1.1`)

Update unsupported backends response code (400)

---

website/content/docs/security/advanced.md

Thanks to our collaborators at CTDS, Funnel is adding support for "Per-User/Per-Bucket" credentials to allow Users to access S3 Buckets without having to store their credentials in the Funnel Server.
The high level overview of this feature will be such Funnel will be able to speak with a custom credential "Wrapper Script" that will:
- Take the User Credentials
- Create an S3 Bucket
- Generate a Key (optionally for use in Nextflow Config)
- Send the Key to Funnel
In this way this Wrapper can manage the bucket and the keys (the Wrapper would be the middleware between the User and Funnel).
Stay tuned for this feature's development! This feature is being tracked with the following:
- GitHub Branch: https://github.com/ohsu-comp-bio/funnel/tree/feature/credentials
- Pull Request: …

`feature/credentials` Per-User/Per-Bucket Support

---

worker/kubernetes.go

When using the Kubernetes compute backend, the Funnel Worker fails when trying to read the logs of the Executor before the Executor Pod has fully started. This then results in a Error loop due to not having a retry mechanism in place. 
This PR resolves this issue by adding retry mechanisms in two places:
1. Creating the [Executor Job](https://github.com/ohsu-comp-bio/funnel/blob/develop/worker/kubernetes.go#L98)
2. Reading the [Executor Logs](https://github.com/ohsu-comp-bio/funnel/blob/develop/worker/kubernetes.go#L112-L117)
This PR is made possible by testing and development recommendations by the [CTDS Team](https://ctds.uchicago.edu/) of [Pauline Ribeyre](https://github.com/paulineribeyre), [Jawad Qureshi](https://github.com/jawadqur), [Aidan Hilt](https://github.com/AidanHilt), and …

`fix/k8s` → `development`: Add Retry Logic to Executor Job and Logs

---

go.mod
tes/utils_test.go

Cleaning up errors in the GitHub Actions workflows.
Current Actions are failing on many workflows due to a mix of dependency issues (`go mod tidy`, deprecated fields).
All actions succeed for all tests defined in the [`.github/workflows`](https://github.com/ohsu-comp-bio/funnel/pull/1195/files) directory

`master` ← `fix/github-actions` — Update GitHub Actions workflows 🐛 
